baseURL = "https://learndevtools.now.sh/"
languageCode = "en-us"
title = "Learn DevTools"
theme = "book"
googleAnalytics = "UA-118017469-13"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5